#Controller script for the biped walker#

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
#  extra_joints:
#    - name:     'extra1'
#      position: 10.0
#      velocity: 20.0
# #     effort:   30.0
#    - name:     'extra2'
#      position: -10.0
#    - name:     'extra3'

# Effort Controllers & Position Controllers
chassis_world_effort_controller:
  type: effort_controllers/JointEffortController
#  type: effort_controllers/JointPositionController
  joint: chassis_world
  pid: {p: 1, i: 0.001, d: 0.065}
#  pid: {p: 10, i: 0.1, d: 10}



